Added WIP

diff --git a/server/docker-base/Dockerfile b/server/docker-base/Dockerfile
--- a/server/docker-base/Dockerfile
+++ b/server/docker-base/Dockerfile
@@ -1,24 +1,55 @@
-FROM ubuntu:16.04
-
-# We updated to use clang-9 for linux in 1.2.171
-# So once that is the last supported version, we can remove support for GCC5 etc
+FROM ubuntu:20.04
 
 # Base stuff
+# RUN \
+#   echo "LINUX TOOLS + COMPILER" && \
+#   dpkg --add-architecture i386 && \
+#   apt-get update && \
+#   apt-get install -y software-properties-common && \
+#   add-apt-repository ppa:openjdk-r/ppa && \
+#   apt-get update && \
+#   apt-get install -y --no-install-recommends \
+#     wget \
+#     locales \
+#     openjdk-17-jdk \
+#     # gcc \
+#     # g++ \
+#     # gcc-multilib \
+#     # g++-multilib \
+#     libssl-dev \
+#     openssl \
+#     libtool \
+#     autoconf \
+#     automake \
+#     uuid-dev \
+#     libxi-dev \
+#     libopenal-dev \
+#     libgl1-mesa-dev \
+#     libglw1-mesa-dev \
+#     freeglut3-dev \
+#     zlib1g:i386 && \
+#     unzip \
+#     # for use when debugging
+#     tree \
+#     silversearcher-ag \
+#     less \
+#     nano \
+# # cleanup
+#   rm -rf /var/lib/apt/lists/*
+
 RUN \
   echo "LINUX TOOLS + COMPILER" && \
-  dpkg --add-architecture i386 && \
   apt-get update && \
   apt-get install -y software-properties-common && \
-  add-apt-repository ppa:openjdk-r/ppa && \
   apt-get update && \
   apt-get install -y --no-install-recommends \
     wget \
     locales \
-    openjdk-11-jdk \
-    gcc \
-    g++ \
-    gcc-multilib \
-    g++-multilib \
+    openjdk-17-jdk \
+    # gcc \
+    # g++ \
+    # gcc-multilib \
+    # g++-multilib \
     libssl-dev \
     openssl \
     libtool \
@@ -31,44 +62,46 @@ RUN \
     libglw1-mesa-dev \
     freeglut3-dev \
     unzip \
+    # for use when debugging
     tree \
     silversearcher-ag \
     less \
     nano \
-    zlib1g:i386 && \
+    && \
 # cleanup
-  rm -rf /var/lib/apt/lists/*
+  apt-get clean autoclean autoremove
 
-ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
 
-# To avoid the mysterious error "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"
-# # From https://github.com/docker-library/openjdk/blob/master/11/jdk/slim/Dockerfile
-RUN \
-  apt-get update; \
-  apt-get install -y --no-install-recommends \
-# utilities for keeping Debian and OpenJDK CA certificates in sync
-    ca-certificates p11-kit \
-  ; \
-# update "cacerts" bundle to use Debian's CA certificates (and make sure it stays up-to-date with changes to Debian's store)
-# see https://github.com/docker-library/openjdk/issues/327
-#     http://rabexc.org/posts/certificates-not-working-java#comment-4099504075
-#     https://salsa.debian.org/java-team/ca-certificates-java/blob/3e51a84e9104823319abeb31f880580e46f45a98/debian/jks-keystore.hook.in
-#     https://git.alpinelinux.org/aports/tree/community/java-cacerts/APKBUILD?id=761af65f38b4570093461e6546dcf6b179d2b624#n29
-  { \
-    echo '#!/usr/bin/env bash'; \
-    echo 'set -Eeuo pipefail'; \
-    echo 'if ! [ -d "$JAVA_HOME" ]; then echo >&2 "error: missing JAVA_HOME environment variable"; exit 1; fi'; \
-# 8-jdk uses "$JAVA_HOME/jre/lib/security/cacerts" and 8-jre and 11+ uses "$JAVA_HOME/lib/security/cacerts" directly (no "jre" directory)
-    echo 'cacertsFile=; for f in "$JAVA_HOME/lib/security/cacerts" "$JAVA_HOME/jre/lib/security/cacerts"; do if [ -e "$f" ]; then cacertsFile="$f"; break; fi; done'; \
-    echo 'if [ -z "$cacertsFile" ] || ! [ -f "$cacertsFile" ]; then echo >&2 "error: failed to find cacerts file in $JAVA_HOME"; exit 1; fi'; \
-    echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$cacertsFile"'; \
-  } > /etc/ca-certificates/update.d/docker-openjdk; \
-  chmod +x /etc/ca-certificates/update.d/docker-openjdk; \
-  /etc/ca-certificates/update.d/docker-openjdk; \
-  \
-# https://github.com/docker-library/openjdk/issues/331#issuecomment-498834472
-  find "$JAVA_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf; \
-  ldconfig;
+# ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
+
+# # To avoid the mysterious error "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"
+# # # From https://github.com/docker-library/openjdk/blob/master/11/jdk/slim/Dockerfile
+# RUN \
+#   apt-get update; \
+#   apt-get install -y --no-install-recommends \
+# # utilities for keeping Debian and OpenJDK CA certificates in sync
+#     ca-certificates p11-kit \
+#   ; \
+# # update "cacerts" bundle to use Debian's CA certificates (and make sure it stays up-to-date with changes to Debian's store)
+# # see https://github.com/docker-library/openjdk/issues/327
+# #     http://rabexc.org/posts/certificates-not-working-java#comment-4099504075
+# #     https://salsa.debian.org/java-team/ca-certificates-java/blob/3e51a84e9104823319abeb31f880580e46f45a98/debian/jks-keystore.hook.in
+# #     https://git.alpinelinux.org/aports/tree/community/java-cacerts/APKBUILD?id=761af65f38b4570093461e6546dcf6b179d2b624#n29
+#   { \
+#     echo '#!/usr/bin/env bash'; \
+#     echo 'set -Eeuo pipefail'; \
+#     echo 'if ! [ -d "$JAVA_HOME" ]; then echo >&2 "error: missing JAVA_HOME environment variable"; exit 1; fi'; \
+# # 8-jdk uses "$JAVA_HOME/jre/lib/security/cacerts" and 8-jre and 11+ uses "$JAVA_HOME/lib/security/cacerts" directly (no "jre" directory)
+#     echo 'cacertsFile=; for f in "$JAVA_HOME/lib/security/cacerts" "$JAVA_HOME/jre/lib/security/cacerts"; do if [ -e "$f" ]; then cacertsFile="$f"; break; fi; done'; \
+#     echo 'if [ -z "$cacertsFile" ] || ! [ -f "$cacertsFile" ]; then echo >&2 "error: failed to find cacerts file in $JAVA_HOME"; exit 1; fi'; \
+#     echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$cacertsFile"'; \
+#   } > /etc/ca-certificates/update.d/docker-openjdk; \
+#   chmod +x /etc/ca-certificates/update.d/docker-openjdk; \
+#   /etc/ca-certificates/update.d/docker-openjdk; \
+#   \
+# # https://github.com/docker-library/openjdk/issues/331#issuecomment-498834472
+#   find "$JAVA_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf; \
+#   ldconfig;
 
 
 # Add extender user
@@ -86,7 +119,8 @@ RUN mkdir $PLATFORMSDK_DIR
 
 # These packages are downloaded from here: https://github.com/llvm/llvm-project/releases/
 # and then uploaded as-is to S3
-RUN wget -q -O - ${DM_PACKAGES_URL}/clang%2Bllvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz | tar xJ -C /usr/local --strip-components=1
+RUN wget -q -O - ${DM_PACKAGES_URL}/clang%2Bllvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz | tar xJ -C /usr/local --strip-components=1
+#RUN wget -q -O - ${DM_PACKAGES_URL}/clang%2Bllvm-10.0.1-x86_64-linux-gnu-ubuntu-20.04.tar.xz | tar xJ -C /usr/local --strip-components=1
 
 # Darwin
 RUN locale-gen en_US.UTF-8
@@ -114,36 +148,36 @@ RUN \
 
 ENV EMCC_SKIP_SANITY_CHECK 1
 
-## Emscripten 1.39.16 (from version 1.2.170)
-ENV EMSCRIPTEN_SDK_1_39_16 ${PLATFORMSDK_DIR}/emsdk-1.39.16
-ENV EMSCRIPTEN_HOME_1_39_16 ${EMSCRIPTEN_SDK_1_39_16}
-ENV EMSCRIPTEN_CONFIG_1_39_16 ${EMSCRIPTEN_HOME_1_39_16}/.emscripten
-ENV EMSCRIPTEN_BIN_1_39_16 ${EMSCRIPTEN_HOME_1_39_16}/upstream/emscripten
-ENV EMSCRIPTEN_CACHE_1_39_16 /var/extender/emcache_1_39_16
-# Setup a special env variable that will be prefixed to PATH if requested version is 1.39.16
-ENV EMSCRIPTEN_PATH_1_39_16 ${EMSCRIPTEN_HOME_1_39_16}:${EMSCRIPTEN_HOME_1_39_16}/upstream/bin:${EMSCRIPTEN_HOME_1_39_16}/node/12.9.1_64bit/bin:${EMSCRIPTEN_BIN_1_39_16}
+# ## Emscripten 1.39.16 (from version 1.2.170)
+# ENV EMSCRIPTEN_SDK_1_39_16 ${PLATFORMSDK_DIR}/emsdk-1.39.16
+# ENV EMSCRIPTEN_HOME_1_39_16 ${EMSCRIPTEN_SDK_1_39_16}
+# ENV EMSCRIPTEN_CONFIG_1_39_16 ${EMSCRIPTEN_HOME_1_39_16}/.emscripten
+# ENV EMSCRIPTEN_BIN_1_39_16 ${EMSCRIPTEN_HOME_1_39_16}/upstream/emscripten
+# ENV EMSCRIPTEN_CACHE_1_39_16 /var/extender/emcache_1_39_16
+# # Setup a special env variable that will be prefixed to PATH if requested version is 1.39.16
+# ENV EMSCRIPTEN_PATH_1_39_16 ${EMSCRIPTEN_HOME_1_39_16}:${EMSCRIPTEN_HOME_1_39_16}/upstream/bin:${EMSCRIPTEN_HOME_1_39_16}/node/12.9.1_64bit/bin:${EMSCRIPTEN_BIN_1_39_16}
 
-RUN \
-  mkdir ${EMSCRIPTEN_SDK_1_39_16} && \
-  wget -q -O - ${DM_PACKAGES_URL}/emsdk-1.39.16-linux.tar.gz | tar xz -C ${EMSCRIPTEN_SDK_1_39_16} --strip-components=1
+# RUN \
+#   mkdir ${EMSCRIPTEN_SDK_1_39_16} && \
+#   wget -q -O - ${DM_PACKAGES_URL}/emsdk-1.39.16-linux.tar.gz | tar xz -C ${EMSCRIPTEN_SDK_1_39_16} --strip-components=1
 
-RUN \
-  ${EMSCRIPTEN_HOME_1_39_16}/emsdk activate sdk-1.39.16-64bit --embedded && \
-  EM_CONFIG=$EMSCRIPTEN_CONFIG_1_39_16 EM_CACHE=${EMSCRIPTEN_CACHE_1_39_16} python ${EMSCRIPTEN_BIN_1_39_16}/embuilder.py build SYSTEM MINIMAL && \
-  chmod -R 755 ${EMSCRIPTEN_HOME_1_39_16} && \
-  chown -R extender: ${EMSCRIPTEN_CACHE_1_39_16} && \
-  chown -R extender: ${EMSCRIPTEN_CACHE_1_39_16}.lock
+# RUN \
+#   ${EMSCRIPTEN_HOME_1_39_16}/emsdk activate sdk-1.39.16-64bit --embedded && \
+#   EM_CONFIG=$EMSCRIPTEN_CONFIG_1_39_16 EM_CACHE=${EMSCRIPTEN_CACHE_1_39_16} python ${EMSCRIPTEN_BIN_1_39_16}/embuilder.py build SYSTEM MINIMAL && \
+#   chmod -R 755 ${EMSCRIPTEN_HOME_1_39_16} && \
+#   chown -R extender: ${EMSCRIPTEN_CACHE_1_39_16} && \
+#   chown -R extender: ${EMSCRIPTEN_CACHE_1_39_16}.lock
 
 ## Emscripten 2.0.11 (from version 1.2.178)
 
 RUN \
-  add-apt-repository ppa:deadsnakes/ppa && \
-  apt-get autoclean && \
-  apt-get update && \
-  apt-get clean autoclean autoremove && \
-  apt-get install -y --no-install-recommends python3.9 && \
-  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1 && \
-  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2 && \
+  # add-apt-repository ppa:deadsnakes/ppa && \
+  # apt-get autoclean && \
+  # apt-get update && \
+  # apt-get clean autoclean autoremove && \
+  # apt-get install -y --no-install-recommends python3.9 && \
+  # update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
+  # update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2 && \
   python3 --version
 
 ENV EMSCRIPTEN_SDK_2_0_11 ${PLATFORMSDK_DIR}/emsdk-2.0.11
@@ -174,12 +208,13 @@ RUN chmod -R 755 ${EMSCRIPTEN_TEMP_DIR} && chown extender: ${EMSCRIPTEN_TEMP_DIR
 # The "sed" command below removes the /TEMP_DIR line from the generated configs
 # We replace it with a folder of our own
 RUN sed '/TEMP_DIR =/d' ${EMSCRIPTEN_CONFIG_2_0_11} && \
-  echo TEMP_DIR = \'${EMSCRIPTEN_TEMP_DIR}\' >> ${EMSCRIPTEN_CONFIG_2_0_11} && \
-  sed '/TEMP_DIR =/d' ${EMSCRIPTEN_CONFIG_1_39_16} && \
-  echo TEMP_DIR = \'${EMSCRIPTEN_TEMP_DIR}\' >> ${EMSCRIPTEN_CONFIG_1_39_16}
+  echo TEMP_DIR = \'${EMSCRIPTEN_TEMP_DIR}\' >> ${EMSCRIPTEN_CONFIG_2_0_11}
+  #  && \
+  # sed '/TEMP_DIR =/d' ${EMSCRIPTEN_CONFIG_1_39_16} && \
+  # echo TEMP_DIR = \'${EMSCRIPTEN_TEMP_DIR}\' >> ${EMSCRIPTEN_CONFIG_1_39_16}
 
-RUN \
-  update-alternatives --set python3 /usr/bin/python3.5
+# RUN \
+#   update-alternatives --set python3 /usr/bin/python3.5
 
 
 #
@@ -386,7 +421,7 @@ RUN \
   apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main" && \
   dpkg --add-architecture i386 && \
   apt-get update && \
-  DEBIAN_FRONTEND="noninteractive" apt-get install -y --install-recommends winehq-stable && \
+  DEBIAN_FRONTEND="noninteractive" apt-get install -y --install-recommends winehq-stable winetricks && \
   apt-get clean autoclean autoremove && \
   rm winehq.key
 
@@ -410,8 +445,9 @@ ENV DISPLAY=":1"
 RUN \
   set -xe                     && \
   WINEDLLOVERRIDES="mscoree,mshtml=" xvfb-run wine wineboot && \
-  xvfb-run wineserver -w      && \
-  xvfb-run winetricks -q vcrun2015
+  xvfb-run wineserver -w
+  # xvfb-run wineserver -w      && \
+  # xvfb-run winetricks -q vcrun2015
 
 RUN \
   chown -R extender: $WINEPREFIX
@@ -464,13 +500,13 @@ ENV SWIFT_5_VERSION         5.0
 # The updated install flow
 RUN \
   apt-get update && \
-  apt-get install -y git cmake && \
+  apt-get install -y git cmake build-essential && \
   cd /tmp && \
   TAPITMP=/usr/local/tapi1.6 && \
   mkdir $TAPITMP && \
   git clone https://github.com/tpoechtrager/apple-libtapi.git && \
   cd apple-libtapi && \
-  git checkout a66284251b46d591ee4a0cb4cf561b92a0c138d8 && \
+  git checkout 664b8414f89612f2dfd35a9b679c345aa5389026 && \
   INSTALLPREFIX=$TAPITMP ./build.sh && \
   ./install.sh && \
   cd .. && \
